name: check
on: [push, pull_request]
jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install flake8
      run: |
        pip install flake8 flake8-import-order flake8-commas flake8-logging-format
    - name: Run flake8
      run: |
        flake8 --version
        flake8
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install mypy
      run: |
        pip install mypy
    - name: Run mypy
      run: |
        mypy --version
        mypy nginx_krbauth.py
